version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
    networks:
      - kafka
  kafka:
    image: wurstmeister/kafka:2.11-2.0.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 172.17.0.1
      KAFKA_CREATE_TOPICS: "event.operations.specific.deposits.currentaccount.created:1:1,event.operations.specific.deposits.currentaccount.opened:1:1,event.operations.specific.deposits.currentaccount.failed:1:1,event.operations.cross.accountmngmt.frauddetection.checked:1:1,event.sales.customermngmt.creditrating.checked:1:1,event.sales.servicing.cardcase.issued:1:1,event.operations.specific.deposits.savingsaccount.opened:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    networks:
      - kafka
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  kafka:
